# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  weight = 10

[[main]]
  name = "Home "
  url = "#posts"
  parent = "Home"
  weight = 10

[[main]]
  name = "About us"
  url = "#about"
  parent="Home"
  weight = 20

[[main]]
  name = "People"
  url = "#people"
  parent = "Home"
  weight = 30

[[main]]
  name = "Photos"
  url = "photos"
  parent="Home"
  weight = 40
#-------------------------------------

[[main]]
  name = "Advocate"
  url = "education_advocacy"
  weight = 15

# engage-----------------------------
[[main]]
  name = "Engage"
  weight = 20

[[main]]
  name = "Donate & Support"
  url = "donate"
  parent = "Engage"
  weight = 20

[[main]]
  name = "Get Involved"
  url = "get_involved"
  parent = "Engage"
  weight = 30

[[main]]
  name = "Volunteer & Events"
  url = "events"
  parent="Engage"
  weight = 40

# trails-----------------------------
[[main]]
  name = "Trails & Facilities"
  url = "#trails"
  weight = 30

[[main]]
  name = "Pump Track at Walker Park"
  url = "pump-track"
  parent="Trails & Facilities"
  weight = 10

[[main]]
  name = "Walker Park Trails"
  url = "trails/trail-creek/"
  parent="Trails & Facilities"
  weight = 20

[[main]]
  name = "Heritage Park Trails"
  url = "trails/heritage-park/"
  parent="Trails & Facilities"
  weight = 30

[[main]]
  name = "Hawkes Creek Farm Trails"
  url = "https://hartfarmtrails.com/"
  parent="Trails & Facilities"
  weight = 40

[[main]]
  name = "Hart Farm Trails"
  url = "hawkes-creek"
  parent="Trails & Facilities"
  weight = 40

[[main]]
  name = "UGA Intramural Fields"
  url = "uga-intramural"
  parent="Trails & Facilities"
  weight = 50

#-------------------------------------

[[main]]
  name = "Join"
  url = "join"
  parent="Engage"
  weight = 70

[[main]]
    name = "Store"
    url = "https://sorba-athens.myshopify.com/"
    weight = 80

# Link to a PDF
# To enable, copy to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 90
