# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Get Involved"
  url = "get_involved"
  weight = 20

[[main]]
  name = "Trails"
  url = "#trails"
  weight = 30

[[main]]
  name = "News"
  url = "#posts"
  weight = 35

[[main]]
  name = "Events"
  url = "events"
  weight = 40

[[main]]
  name = "Photos"
  url = "photos"
  weight = 50

[[main]]
  name = "Board"
  url = "#people"
  weight = 60

[[main]]
  name = "Join"
  url = "https://www.imba.com/renew/chapter/sorba-athens"
  weight = 70

[[main]]
  name = "Donate"
  url = "donate"
  weight = 80

[[main]]
  name = "Pump Track"
  url = "pump-track"
  weight = 32

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 90
